In [11]:
#1
import numpy as np
o=np.ones(3)
print(o)
print(o.ndim)
t=np.ones((2,1))
print(t)
print(t.ndim)
three=np.ones((3,2,1))
print(three)
print(three.ndim)

[1. 1. 1.]
1
[[1.]
 [1.]]
2
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]]
3


In [13]:
#2
a=np.arange(9)
print(a.shape)
a=a.reshape((3,3))
print(a.shape)

(9,)
(3, 3)


In [14]:
#3
l=list(range(1,10))
print(type(l))
a=np.array(l)
print(type(a))

<class 'list'>
<class 'numpy.ndarray'>


In [15]:
#4
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
#5
np.linspace(4,6,5)

array([4. , 4.5, 5. , 5.5, 6. ])

In [98]:
#6
print(np.logspace(2,3,5))
print(np.logspace(2,3,5,base=2.0))

[ 100.          177.827941    316.22776602  562.34132519 1000.        ]
[4.         4.75682846 5.65685425 6.72717132 8.        ]


In [28]:
#7
np.full((2,3),11)

array([[11, 11, 11],
       [11, 11, 11]])

In [29]:
#8
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
#9
np.random.rand(3,2)

array([[0.91988703, 0.80397996],
       [0.66926644, 0.19586735],
       [0.85756534, 0.24817791]])

In [34]:
np.random.randn(3,2)

array([[ 1.00414661,  0.37579112],
       [-0.06042236,  0.29481372],
       [-0.55279812, -1.78677095]])

In [38]:
np.random.randint(0,10)

6

In [43]:
#10
i=np.identity(3)
print("Identity matrix :")
print(i)
d=np.diag(i)
print("Diagonal matrix :")
print(d)

Identity matrix :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Diagonal matrix :
[1. 1. 1.]


In [48]:
#11
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]])
print("shape :",a.shape)
a[1][0][2]

shape : (2, 2, 3)


9

In [55]:
#12
a=np.arange(10)
print(a)
s1=a[3:7]
print(s1)
s1[:]=24
print(a)
print(s1)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[ 0  1  2 24 24 24 24  7  8  9]
[24 24 24 24]


In [62]:
#13
a=np.array([[1,2,3],[4,12,9],[10,0,1]])
print(a)
s=a[:,1:2]
print(s)
s1=a[0:2,0:1]
print(s1)

[[ 1  2  3]
 [ 4 12  9]
 [10  0  1]]
[[ 2]
 [12]
 [ 0]]
[[1]
 [4]]


In [94]:
#14
a=np.array([[1,2],[3,5],[7,56]])
print(a)
at=a.T
print("Transpose :")
print(at)
flr=np.fliplr(a)
print("Flip left-right :")
print(flr)
fud=np.flipud(a)
print("Flip up-down :")
print(fud)
r=np.rot90(a)
print("Rotate 90 :")
print(r)

[[ 1  2]
 [ 3  5]
 [ 7 56]]
Transpose :
[[ 1  3  7]
 [ 2  5 56]]
Flip left-right :
[[ 2  1]
 [ 5  3]
 [56  7]]
Flip up-down :
[[ 7 56]
 [ 3  5]
 [ 1  2]]
Rotate 90 :
[[ 2  5 56]
 [ 1  3  7]]


In [97]:
#15
a=np.array([[1,2,3],[4,5,6]])
v=np.vstack((a,np.array([10,20,30])))
print("Vertical stack :")
print(v)
h=np.hstack((a,np.array([[10],[20]])))
print("Horizontal stack :")
print(h)

Vertical stack :
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]
Horizontal stack :
[[ 1  2  3 10]
 [ 4  5  6 20]]
